FROM node:10.0

# Create app directory
WORKDIR /usr/src/app

# get files
COPY . .

# install dependencies
RUN npm install donejs -g
RUN npm install

# expose your ports
EXPOSE 7070

# start it up
CMD [ "donejs", "api" ]
