#!/bin/bash


echo "Building pmo-api ..."
docker build -f Dockerfile-api -t donejs/place-my-order-api .
echo "Building pmo-api ... Done"


echo "Building pmo ..."
docker build -f Dockerfile -t donejs/place-my-order .
echo "Building pmo ... Done"

